name: fish_clicker
description: "Fish Clicker"
publish_to: "none"
version: 1.0.3

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.0
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  gif: ^2.3.0
  just_audio: ^0.10.5
  package_info_plus: ^9.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/spinning_fish.gif
    - assets/fish.png
    - assets/fish_slap.mp3
    - assets/goldfish.mp3

  fonts:
    - family: BabyDoll
      fonts:
        - asset: assets/BabyDoll.ttf
